version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/shophive
      - JWT_SECRET=your_jwt_secret_key
      - PORT=5000
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: shophive_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
